const XIN_CHAO = 'XIN_CHAO'
const KET_THUC = 'KET_THUC'
const LAY_SDT = 'LAY_SDT'
const ASK_SKU = 'ASK_SKU'
const CON_HANG = 'CON_HANG'
const HET_HANG = 'HET_HANG'
const CHECK_PRODUCT = 'CHECK_PRODUCT'
module.exports = { XIN_CHAO, KET_THUC, LAY_SDT, ASK_SKU, HET_HANG, CON_HANG }
